services:
  app:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8000:80
    environment:
      - ENV=production
      - DB_USER=postgres
      - DB_PASS=PASS
      - DB_HOST=HOST
      - DB_PORT=5432
      - DB_NAME=DB
      - DB_SCHEMA=convoy

