// This file is auto-generated by @hey-api/openapi-ts

export type APIResponse = {
    message: string;
    status: Status;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Machine = {
    id?: string;
    meter_unit: string;
    make: string;
    model: string;
    year: number;
    image: string;
    purchase_date?: Date | null;
};

export type MachineCreate = {
    make: string;
    model: string;
    year: number;
    image?: string | null;
    meter_unit: string;
};

export type MachineDetailed = {
    id: string;
    make: string;
    model: string;
    year: number;
    image?: string | null;
    meter_unit: string;
    meter_readings: Array<MeterReading>;
    task_definitions: Array<TaskDefinition>;
    tasks: Array<TaskDetailed>;
    readonly current_meter_reading: number | null;
    readonly name: number;
};

export type MeterReading = {
    id?: string;
    value: number;
    timestamp?: Date;
    machine_id?: string | null;
};

export type Part = {
    id?: string;
    name: string;
    link?: string | null;
    supply_id?: string;
};

export type Status = 'SUCCESS' | 'ERROR';

export type Supply = {
    id?: string;
    name: string;
    unit: string;
    quantity_on_hand?: number;
    machine_id?: string | null;
};

export type SupplyDetailed = {
    id?: string;
    name: string;
    unit: string;
    quantity_on_hand?: number;
    parts?: Array<Part>;
    machine_id: string | null;
};

export type Task = {
    id?: string;
    completed?: boolean;
    completed_date?: Date | null;
    completed_meter_reading?: number | null;
    due_date: Date;
    due_meter_reading?: number;
    notes?: string | null;
    task_definition_id?: string | null;
    machine_id?: string | null;
};

export type TaskComplete = {
    id: string;
    completed?: boolean;
    completed_date: Date;
    completed_meter_reading: number;
    notes?: string | null;
};

export type TaskDefinition = {
    id?: string;
    description: string;
    time_interval: number;
    meter_interval: number;
    recurring?: boolean | null;
    notes?: string | null;
    machine_id?: string | null;
};

export type TaskDefinitionCreate = {
    description: string;
    time_interval: number;
    meter_interval: number;
    recurring?: boolean | null;
    notes?: string | null;
    machine_id: string | null;
    initial_due_meter?: number | null;
    initial_due_date?: Date | null;
};

export type TaskDefinitionDetailed = {
    id: string;
    description: string;
    time_interval: number;
    meter_interval: number;
    recurring?: boolean | null;
    notes?: string | null;
    machine_id: string | null;
    supplies: Array<TaskSupplyDetailed>;
};

export type TaskDetailed = {
    id?: string;
    completed?: boolean;
    completed_date?: Date | null;
    completed_meter_reading?: number | null;
    due_date: Date;
    due_meter_reading?: number;
    notes?: string | null;
    task_definition_id: string | null;
    task_definition: TaskDefinitionDetailed | null;
    machine_id: string | null;
    machine: Machine;
    readonly due_meter_ago: number;
    readonly due_days_ago: number;
    readonly overdue_reason: string;
};

export type TaskSupply = {
    id?: string;
    quantity?: number;
    task_definition_id?: string | null;
    supply_id?: string | null;
};

export type TaskSupplyDetailed = {
    id: string;
    quantity?: number;
    supply: SupplyDetailed;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type GetMachinesResponse = Array<MachineDetailed>;

export type CreateMachineData = {
    requestBody: MachineCreate;
};

export type CreateMachineResponse = Machine;

export type GetSuppliesResponse = Array<SupplyDetailed>;

export type CreateSupplyData = {
    requestBody: Supply;
};

export type CreateSupplyResponse = Supply;

export type DeleteSupplyData = {
    supplyId: unknown;
};

export type DeleteSupplyResponse = Supply;

export type UpdateSupplyData = {
    requestBody: Supply;
    supplyId: string;
};

export type UpdateSupplyResponse = Supply;

export type AssignSuppliesData = {
    machineId: string;
    requestBody: Array<TaskSupply>;
    taskDefId: string;
};

export type AssignSuppliesResponse = APIResponse;

export type GetMachineData = {
    machineId: string;
};

export type GetMachineResponse = Machine;

export type DeleteMachineData = {
    machineId: string;
};

export type DeleteMachineResponse = Machine;

export type UpdateMachineData = {
    machineId: string;
    requestBody: MachineCreate;
};

export type UpdateMachineResponse = Machine;

export type GetReadingsData = {
    machineId: string;
};

export type GetReadingsResponse = Array<MeterReading>;

export type CreateReadingData = {
    machineId: string;
    requestBody: MeterReading;
};

export type CreateReadingResponse = MeterReading;

export type GetReadingData = {
    machineId: string;
    readingId: string;
};

export type GetReadingResponse = MeterReading;

export type GetTasksData = {
    machineId: string;
};

export type GetTasksResponse = Array<TaskDetailed>;

export type GetTaskData = {
    machineId: string;
    taskId: string;
};

export type GetTaskResponse = TaskDetailed;

export type GetTaskDefinitionsData = {
    machineId: string;
};

export type GetTaskDefinitionsResponse = Array<TaskDefinition>;

export type CreateTaskDefinitionData = {
    machineId: string;
    requestBody: TaskDefinitionCreate;
};

export type CreateTaskDefinitionResponse = TaskDefinition;

export type GetTaskDefinitionData = {
    machineId: string;
    taskDefinitionId: string;
};

export type GetTaskDefinitionResponse = TaskDefinition;

export type DeleteTaskData = {
    taskId: string;
};

export type DeleteTaskResponse = Task;

export type DeleteTaskDefinitionData = {
    taskId: string;
};

export type DeleteTaskDefinitionResponse = TaskDefinition;

export type CompleteTaskData = {
    requestBody: TaskComplete;
    taskId: string;
};

export type CompleteTaskResponse = Task;

export type $OpenApiTs = {
    '/api/v1/machines': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<MachineDetailed>;
            };
        };
        post: {
            req: CreateMachineData;
            res: {
                /**
                 * Successful Response
                 */
                200: Machine;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/supplies': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: Array<SupplyDetailed>;
            };
        };
        post: {
            req: CreateSupplyData;
            res: {
                /**
                 * Successful Response
                 */
                200: Supply;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/supplies/{supply_id}': {
        delete: {
            req: DeleteSupplyData;
            res: {
                /**
                 * Successful Response
                 */
                200: Supply;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: UpdateSupplyData;
            res: {
                /**
                 * Successful Response
                 */
                200: Supply;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}/task_definitions/{task_def_id}/supplies': {
        post: {
            req: AssignSuppliesData;
            res: {
                /**
                 * Successful Response
                 */
                200: APIResponse;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}': {
        get: {
            req: GetMachineData;
            res: {
                /**
                 * Successful Response
                 */
                200: Machine;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        delete: {
            req: DeleteMachineData;
            res: {
                /**
                 * Successful Response
                 */
                200: Machine;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        patch: {
            req: UpdateMachineData;
            res: {
                /**
                 * Successful Response
                 */
                200: Machine;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}/readings': {
        get: {
            req: GetReadingsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<MeterReading>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: CreateReadingData;
            res: {
                /**
                 * Successful Response
                 */
                200: MeterReading;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}/readings/{reading_id}': {
        get: {
            req: GetReadingData;
            res: {
                /**
                 * Successful Response
                 */
                200: MeterReading;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}/tasks': {
        get: {
            req: GetTasksData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<TaskDetailed>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}/tasks/{task_id}': {
        get: {
            req: GetTaskData;
            res: {
                /**
                 * Successful Response
                 */
                200: TaskDetailed;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}/task_definitions': {
        get: {
            req: GetTaskDefinitionsData;
            res: {
                /**
                 * Successful Response
                 */
                200: Array<TaskDefinition>;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
        post: {
            req: CreateTaskDefinitionData;
            res: {
                /**
                 * Successful Response
                 */
                200: TaskDefinition;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/machines/{machine_id}/task_definitions/{task_definition_id}': {
        get: {
            req: GetTaskDefinitionData;
            res: {
                /**
                 * Successful Response
                 */
                200: TaskDefinition;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/tasks/{task_id}': {
        delete: {
            req: DeleteTaskData;
            res: {
                /**
                 * Successful Response
                 */
                200: Task;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/task_definitions/{task_id}': {
        delete: {
            req: DeleteTaskDefinitionData;
            res: {
                /**
                 * Successful Response
                 */
                200: TaskDefinition;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
    '/api/v1/tasks/{task_id}/complete': {
        post: {
            req: CompleteTaskData;
            res: {
                /**
                 * Successful Response
                 */
                200: Task;
                /**
                 * Validation Error
                 */
                422: HTTPValidationError;
            };
        };
    };
};

export type GetMachinesResponseTransformer = (data: any) => Promise<GetMachinesResponse>;

export type MachineDetailedModelResponseTransformer = (data: any) => MachineDetailed;

export type MeterReadingModelResponseTransformer = (data: any) => MeterReading;

export const MeterReadingModelResponseTransformer: MeterReadingModelResponseTransformer = data => {
    if (data?.timestamp) {
        data.timestamp = new Date(data.timestamp);
    }
    return data;
};

export type TaskDetailedModelResponseTransformer = (data: any) => TaskDetailed;

export const TaskDetailedModelResponseTransformer: TaskDetailedModelResponseTransformer = data => {
    if (data?.due_date) {
        data.due_date = new Date(data.due_date);
    }
    return data;
};

export const MachineDetailedModelResponseTransformer: MachineDetailedModelResponseTransformer = data => {
    if (Array.isArray(data?.meter_readings)) {
        data.meter_readings.forEach(MeterReadingModelResponseTransformer);
    }
    if (Array.isArray(data?.tasks)) {
        data.tasks.forEach(TaskDetailedModelResponseTransformer);
    }
    return data;
};

export const GetMachinesResponseTransformer: GetMachinesResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(MachineDetailedModelResponseTransformer);
    }
    return data;
};

export type GetReadingsResponseTransformer = (data: any) => Promise<GetReadingsResponse>;

export const GetReadingsResponseTransformer: GetReadingsResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(MeterReadingModelResponseTransformer);
    }
    return data;
};

export type CreateReadingResponseTransformer = (data: any) => Promise<CreateReadingResponse>;

export const CreateReadingResponseTransformer: CreateReadingResponseTransformer = async (data) => {
    MeterReadingModelResponseTransformer(data);
    return data;
};

export type GetReadingResponseTransformer = (data: any) => Promise<GetReadingResponse>;

export const GetReadingResponseTransformer: GetReadingResponseTransformer = async (data) => {
    MeterReadingModelResponseTransformer(data);
    return data;
};

export type GetTasksResponseTransformer = (data: any) => Promise<GetTasksResponse>;

export const GetTasksResponseTransformer: GetTasksResponseTransformer = async (data) => {
    if (Array.isArray(data)) {
        data.forEach(TaskDetailedModelResponseTransformer);
    }
    return data;
};

export type GetTaskResponseTransformer = (data: any) => Promise<GetTaskResponse>;

export const GetTaskResponseTransformer: GetTaskResponseTransformer = async (data) => {
    TaskDetailedModelResponseTransformer(data);
    return data;
};

export type DeleteTaskResponseTransformer = (data: any) => Promise<DeleteTaskResponse>;

export type TaskModelResponseTransformer = (data: any) => Task;

export const TaskModelResponseTransformer: TaskModelResponseTransformer = data => {
    if (data?.due_date) {
        data.due_date = new Date(data.due_date);
    }
    return data;
};

export const DeleteTaskResponseTransformer: DeleteTaskResponseTransformer = async (data) => {
    TaskModelResponseTransformer(data);
    return data;
};

export type CompleteTaskResponseTransformer = (data: any) => Promise<CompleteTaskResponse>;

export const CompleteTaskResponseTransformer: CompleteTaskResponseTransformer = async (data) => {
    TaskModelResponseTransformer(data);
    return data;
};