name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        working-directory: ./devices
        run: pio run -e agent -e base-station
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./devices/.pio/build/agent/firmware.bin
            ./devices/.pio/build/base-station/firmware.bin